os: Visual Studio 2015

version: 1.1.8.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
  - ps: Start-FileDownload 'https://download.microsoft.com/download/0/F/D/0FD852A4-7EA1-4E2A-983A-0484AC19B92C/dotnet-sdk-2.0.0-win-gs-x64.exe'
  - cmd: dotnet-sdk-2.0.0-win-gs-x64.exe /quiet
  - ps: $env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = "true"

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\


build_script:
- dotnet build .\src\LinqKit\LinqKit.csproj -f net45 -c %CONFIGURATION% 
- dotnet build .\src\LinqKit.EntityFramework\LinqKit.EntityFramework.csproj -f net45 -c %CONFIGURATION%
- dotnet build .\src\LinqKit.Microsoft.EntityFrameworkCore\LinqKit.Microsoft.EntityFrameworkCore.csproj -f netstandard2.0 -c %CONFIGURATION%

- dotnet build .\tests\LinqKit.Tests\LinqKit.Tests.csproj
- dotnet build .\tests\LinqKit.EntityFramework.Tests.Net452\LinqKit.EntityFramework.Tests.Net452.csproj
- dotnet build .\tests\LinqKit.Microsoft.EntityFrameworkCore.Tests\LinqKit.Microsoft.EntityFrameworkCore.Tests.csproj -c %CONFIGURATION%


test_script:
- dotnet test --no-build .\tests\LinqKit.Tests\LinqKit.Tests.csproj
- dotnet test --no-build .\tests\LinqKit.EntityFramework.Tests.Net452\LinqKit.EntityFramework.Tests.Net452.csproj
- dotnet test --no-build .\tests\LinqKit.Microsoft.EntityFrameworkCore.Tests -c %CONFIGURATION% 


#artifacts:
#- path: artifacts\**\*.*


#cache:
#- '%USERPROFILE%\.nuget\packages'